using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Espresso.SourceGenerator;

/// <summary>
/// Emits the specialized <c>Node&lt;K,V&gt;</c> subclasses. Each cache configuration only pays for the
/// fields its feature set uses, so the generator enumerates the strong-key/strong-value feature
/// matrix and emits one sealed class per combination, overriding just the accessors backed by a
/// field it declares.
/// <para>
/// Naming: <c>P</c> strong key, <c>S</c> strong value, then the optional suffixes <c>A</c> (access
/// time), <c>W</c> (write time), <c>R</c> (refresh), and the eviction flag <c>MS</c> (unweighted
/// maximum) or <c>MW</c> (weighted maximum).
/// </para>
/// </summary>
[Generator]
public sealed class NodeGenerator : IIncrementalGenerator
{
    private const string Namespace = "Espresso.Internal";
    private static readonly bool[] Bools = { false, true };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            var sb = new StringBuilder();
            EmitHeader(sb);

            var names = new List<string>();
            foreach (bool access in Bools)
            foreach (bool write in Bools)
            foreach (bool variable in Bools)
            foreach (bool refresh in Bools)
            foreach (int maximum in new[] { 0, 1, 2 }) // 0 none, 1 size, 2 weight
            {
                var features = new Features(access, write, variable, refresh, maximum);
                string name = features.ClassName();
                names.Add(name);
                EmitNode(sb, features, name);
            }

            EmitFactory(sb, names);
            sb.AppendLine("}"); // namespace

            ctx.AddSource("Nodes.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private readonly struct Features
    {
        public readonly bool Access;
        public readonly bool Write;
        public readonly bool Variable;
        public readonly bool Refresh;
        public readonly int Maximum; // 0 none, 1 size, 2 weight

        public Features(bool access, bool write, bool variable, bool refresh, int maximum)
        {
            Access = access;
            Write = write;
            Variable = variable;
            Refresh = refresh;
            Maximum = maximum;
        }

        public bool UsesMaximum => Maximum != 0;
        public bool Weighted => Maximum == 2;

        // Write time is materialized when either write-expiration or refresh is configured.
        public bool UsesWriteTime => Write || Refresh;

        // An access-order deque is used for the window/main queues (maximum) or access expiration.
        public bool UsesAccessDeque => UsesMaximum || Access;

        // A write-order deque is used only for write expiration.
        public bool UsesWriteDeque => Write;

        public string ClassName()
        {
            var sb = new StringBuilder("PS"); // strong key, strong value
            if (Access) sb.Append('A');
            if (Write) sb.Append('W');
            if (Variable) sb.Append('V');
            if (Refresh) sb.Append('R');
            if (Maximum == 1) sb.Append("MS");
            else if (Maximum == 2) sb.Append("MW");
            return sb.ToString();
        }
    }

    private static void EmitHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine();
        sb.AppendLine($"namespace {Namespace}");
        sb.AppendLine("{");
    }

    private static void EmitNode(StringBuilder sb, Features f, string name)
    {
        sb.AppendLine($"    /// <summary>Generated node variant: {name}.</summary>");
        sb.AppendLine($"    internal sealed class {name}<K, V> : Node<K, V>");
        sb.AppendLine("        where K : notnull");
        sb.AppendLine("        where V : class");
        sb.AppendLine("    {");

        // Constructor: accepts the clock so time-based features can seed their fields.
        sb.AppendLine($"        public {name}(K key, V value, int weight, long now) : base(key, value)");
        sb.AppendLine("        {");
        if (f.Weighted)
        {
            sb.AppendLine("            _weight = weight;");
            sb.AppendLine("            _policyWeight = weight;");
        }
        if (f.Access)
        {
            sb.AppendLine("            Volatile.Write(ref _accessTime, now);");
        }
        if (f.UsesWriteTime)
        {
            sb.AppendLine("            Volatile.Write(ref _writeTime, now & ~1L);");
        }
        sb.AppendLine("        }");

        if (f.Weighted)
        {
            sb.AppendLine();
            sb.AppendLine("        private int _weight;");
            sb.AppendLine("        private int _policyWeight;");
            sb.AppendLine("        public override int Weight { get => Volatile.Read(ref _weight); set => Volatile.Write(ref _weight, value); }");
            sb.AppendLine("        public override int PolicyWeight { get => Volatile.Read(ref _policyWeight); set => Volatile.Write(ref _policyWeight, value); }");
        }

        if (f.UsesMaximum)
        {
            sb.AppendLine();
            sb.AppendLine("        private int _queueType;");
            sb.AppendLine("        public override int QueueType { get => _queueType; set => _queueType = value; }");
        }

        if (f.Access)
        {
            sb.AppendLine();
            sb.AppendLine("        private long _accessTime;");
            sb.AppendLine("        public override long AccessTime { get => Volatile.Read(ref _accessTime); set => Volatile.Write(ref _accessTime, value); }");
        }

        if (f.UsesWriteTime)
        {
            sb.AppendLine();
            sb.AppendLine("        private long _writeTime;");
            sb.AppendLine("        public override long WriteTime { get => Volatile.Read(ref _writeTime); set => Volatile.Write(ref _writeTime, value); }");
            sb.AppendLine("        public override bool CasWriteTime(long expect, long update)");
            sb.AppendLine("            => Interlocked.CompareExchange(ref _writeTime, update, expect) == expect;");
        }

        if (f.Variable)
        {
            sb.AppendLine();
            sb.AppendLine("        private long _variableTime;");
            sb.AppendLine("        public override long VariableTime { get => Volatile.Read(ref _variableTime); set => Volatile.Write(ref _variableTime, value); }");
            sb.AppendLine("        public override bool CasVariableTime(long expect, long update)");
            sb.AppendLine("            => Interlocked.CompareExchange(ref _variableTime, update, expect) == expect;");
            sb.AppendLine("        private Node<K, V>? _prevVariable;");
            sb.AppendLine("        private Node<K, V>? _nextVariable;");
            sb.AppendLine("        public override Node<K, V>? PreviousInVariableOrder { get => _prevVariable; set => _prevVariable = value; }");
            sb.AppendLine("        public override Node<K, V>? NextInVariableOrder { get => _nextVariable; set => _nextVariable = value; }");
        }

        if (f.UsesAccessDeque)
        {
            sb.AppendLine();
            sb.AppendLine("        private Node<K, V>? _prevAccess;");
            sb.AppendLine("        private Node<K, V>? _nextAccess;");
            sb.AppendLine("        public override Node<K, V>? GetPreviousInAccessOrder() => _prevAccess;");
            sb.AppendLine("        public override void SetPreviousInAccessOrder(Node<K, V>? prev) => _prevAccess = prev;");
            sb.AppendLine("        public override Node<K, V>? GetNextInAccessOrder() => _nextAccess;");
            sb.AppendLine("        public override void SetNextInAccessOrder(Node<K, V>? next) => _nextAccess = next;");
        }

        if (f.UsesWriteDeque)
        {
            sb.AppendLine();
            sb.AppendLine("        private Node<K, V>? _prevWrite;");
            sb.AppendLine("        private Node<K, V>? _nextWrite;");
            sb.AppendLine("        public override Node<K, V>? GetPreviousInWriteOrder() => _prevWrite;");
            sb.AppendLine("        public override void SetPreviousInWriteOrder(Node<K, V>? prev) => _prevWrite = prev;");
            sb.AppendLine("        public override Node<K, V>? GetNextInWriteOrder() => _nextWrite;");
            sb.AppendLine("        public override void SetNextInWriteOrder(Node<K, V>? next) => _nextWrite = next;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>Emits the feature enum and a factory mapping features to the right node constructor.</summary>
    private static void EmitFactory(StringBuilder sb, List<string> names)
    {
        sb.AppendLine("    /// <summary>Feature flags selecting a generated node variant.</summary>");
        sb.AppendLine("    [System.Flags]");
        sb.AppendLine("    internal enum NodeFeature");
        sb.AppendLine("    {");
        sb.AppendLine("        None = 0,");
        sb.AppendLine("        ExpireAccess = 1 << 0,");
        sb.AppendLine("        ExpireWrite = 1 << 1,");
        sb.AppendLine("        RefreshWrite = 1 << 2,");
        sb.AppendLine("        MaximumSize = 1 << 3,");
        sb.AppendLine("        MaximumWeight = 1 << 4,");
        sb.AppendLine("        ExpireVariable = 1 << 5,");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Creates the smallest node type that satisfies the requested features.</summary>");
        sb.AppendLine("    internal static class NodeFactory");
        sb.AppendLine("    {");
        sb.AppendLine("        public static Node<K, V> Create<K, V>(NodeFeature features, K key, V value, int weight, long now)");
        sb.AppendLine("            where K : notnull");
        sb.AppendLine("            where V : class");
        sb.AppendLine("        {");
        sb.AppendLine("            bool access = (features & NodeFeature.ExpireAccess) != 0;");
        sb.AppendLine("            bool write = (features & NodeFeature.ExpireWrite) != 0;");
        sb.AppendLine("            bool variable = (features & NodeFeature.ExpireVariable) != 0;");
        sb.AppendLine("            bool refresh = (features & NodeFeature.RefreshWrite) != 0;");
        sb.AppendLine("            int maximum = (features & NodeFeature.MaximumWeight) != 0 ? 2");
        sb.AppendLine("                        : (features & NodeFeature.MaximumSize) != 0 ? 1 : 0;");
        sb.AppendLine("            switch ((access, write, variable, refresh, maximum))");
        sb.AppendLine("            {");

        foreach (bool access in Bools)
        foreach (bool write in Bools)
        foreach (bool variable in Bools)
        foreach (bool refresh in Bools)
        foreach (int maximum in new[] { 0, 1, 2 })
        {
            var f = new Features(access, write, variable, refresh, maximum);
            string a = access ? "true" : "false";
            string w = write ? "true" : "false";
            string v = variable ? "true" : "false";
            string r = refresh ? "true" : "false";
            sb.AppendLine($"                case ({a}, {w}, {v}, {r}, {maximum}): return new {f.ClassName()}<K, V>(key, value, weight, now);");
        }

        sb.AppendLine("                default: return new PS<K, V>(key, value, weight, now);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }
}
